/* Supabase validates the session; database RLS restricts profiles to their owner. */
window.CapeCompassAccount=async function(client,user){
  const panel=document.querySelector('.auth-panel'),details=document.getElementById('account-details'),status=document.getElementById('auth-status'),errorNode=document.getElementById('auth-error');
  let busy=false;
  const say=(text,error=false)=>{(error?errorNode:status).textContent=text;if(error)errorNode.focus()};
  const clear=()=>{status.textContent='';errorNode.textContent=''};
  const profile=document.createElement('form');profile.id='profile-form';profile.innerHTML='<h2>Your personal details</h2><p class="helper">Complete your profile. Address is optional.</p><fieldset id="profile-fields" disabled><div class="profile-grid"><div class="profile-dob-field"><fieldset class="dob-group" aria-describedby="dob-help"><legend>Date of birth</legend><div class="dob-controls"><label for="dob-day"><span>Day</span><select id="dob-day" name="dob_day" autocomplete="bday-day" required><option value="">Day</option></select></label><label for="dob-month"><span>Month</span><select id="dob-month" name="dob_month" autocomplete="bday-month" required><option value="">Month</option></select></label><label for="dob-year"><span>Year</span><select id="dob-year" name="dob_year" autocomplete="bday-year" required><option value="">Year</option></select></label></div><input id="profile-dob" name="date_of_birth" type="hidden"><p id="dob-help" class="helper">Choose your day, month and year of birth.</p></fieldset></div><div><label for="profile-phone">Phone number</label><input id="profile-phone" name="phone" type="tel" autocomplete="tel" required maxlength="16" pattern="\\+[1-9][0-9]{6,14}" aria-describedby="phone-help"><p id="phone-help" class="helper">Include your country calling code, for example +233241234567.</p></div><div><label for="profile-gender">Gender</label><select id="profile-gender" name="gender" required><option value="">Choose gender</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="self_described">Self-described</option><option value="prefer_not_to_say">Prefer not to say</option></select></div><div><label for="profile-country">Country</label><select id="profile-country" name="country" autocomplete="country" required><option value="">Choose country</option></select></div></div><label for="profile-address">Address (optional)</label><textarea id="profile-address" name="address" autocomplete="street-address" rows="3" maxlength="500"></textarea><button class="button auth-submit" type="submit">Save details</button></fieldset><p id="profile-status" class="auth-status" role="status" aria-live="polite"></p></form>';
  const workspace=document.createElement('div');workspace.className='account-workspace';const summary=document.createElement('aside');summary.className='account-summary';summary.setAttribute('aria-label','Account information');const identity=document.createElement('div');identity.className='account-identity';const monogram=document.createElement('span');monogram.className='account-monogram';monogram.textContent=(user.email||'C').charAt(0).toUpperCase();monogram.setAttribute('aria-hidden','true');identity.append(monogram);summary.append(identity);for(const node of [...details.children])summary.append(node);const security=document.createElement('section');security.className='account-security';security.innerHTML='<p class="eyebrow">Account security</p><h3>Signed in</h3><p>Your personal details are accessible only through your account.</p>';summary.insertBefore(security,summary.querySelector('.button'));workspace.append(profile,summary);details.append(workspace);
  const countryCodes='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' ');
  const locale=document.documentElement.lang||'en',names=typeof Intl.DisplayNames==='function'?new Intl.DisplayNames([locale],{type:'region'}):null;
  for(const item of countryCodes.map(code=>({code,name:names?names.of(code):code})).sort((a,b)=>a.name.localeCompare(b.name,locale))){const option=document.createElement('option');option.value=item.code;option.textContent=item.name;option.translate=false;profile.elements.country.append(option)}
  const today=new Date();profile.elements.date_of_birth.max=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');
  const dobDay=profile.elements.dob_day,dobMonth=profile.elements.dob_month,dobYear=profile.elements.dob_year;
  for(let year=today.getFullYear();year>=1900;year--){const option=new Option(String(year),String(year));option.translate=false;dobYear.append(option)}
  function monthNames(){const language=document.documentElement.lang||'en',formatter=new Intl.DateTimeFormat(language,{month:'short',timeZone:'UTC'});for(let month=1;month<=12;month++){let option=dobMonth.querySelector('option[value="'+month+'"]');if(!option){option=new Option('',String(month));option.translate=false;dobMonth.append(option)}option.textContent=formatter.format(new Date(Date.UTC(2000,month-1,1)))}}
  function syncDob(){const selected=dobDay.value,year=Number(dobYear.value),month=Number(dobMonth.value);let count=month?new Date(year||2000,month,0).getDate():31;if(year===today.getFullYear()&&month===today.getMonth()+1)count=today.getDate();for(const option of [...dobDay.options])if(option.value)option.remove();for(let day=1;day<=count;day++){const option=new Option(String(day),String(day));option.translate=false;dobDay.append(option)}dobDay.value=selected&&Number(selected)<=count?selected:'';for(const option of dobMonth.options)if(option.value)option.disabled=year===today.getFullYear()&&Number(option.value)>today.getMonth()+1;if(dobMonth.selectedOptions[0]?.disabled)dobMonth.value='';const value=dobDay.value&&dobMonth.value&&dobYear.value?[dobYear.value,dobMonth.value.padStart(2,'0'),dobDay.value.padStart(2,'0')].join('-'):'';profile.elements.date_of_birth.value=value}
  function restoreDob(){const match=profile.elements.date_of_birth.value.match(/^(\d{4})-(\d{2})-(\d{2})$/);dobYear.value=match?match[1]:'';dobMonth.value=match?String(Number(match[2])):'';syncDob();dobDay.value=match?String(Number(match[3])):'';syncDob()}
  monthNames();syncDob();for(const input of [dobDay,dobMonth,dobYear])input.addEventListener('change',syncDob);
  function localizeCountries(){monthNames();if(typeof Intl.DisplayNames!=='function')return;const code=document.documentElement.lang||'en',display=new Intl.DisplayNames([code],{type:'region'}),select=profile.elements.country,value=select.value;const options=[...select.options].filter(option=>option.value);for(const option of options)option.textContent=display.of(option.value);options.sort((a,b)=>a.textContent.localeCompare(b.textContent,code));for(const option of options)select.append(option);select.value=value}
  document.addEventListener('compasslanguagechange',localizeCountries);
  const profileFields=document.getElementById('profile-fields');
  profile.elements.phone.closest('div').classList.add('profile-phone-field');const signout=document.getElementById('sign-out');panel.append(signout);signout.hidden=false;
  signout.addEventListener('click',async()=>{if(busy)return;busy=true;signout.disabled=true;try{const {error}=await client.auth.signOut({scope:'local'});if(error)throw error;location.replace('sign-in.html')}catch{say('Could not sign out. Please try again.',true);busy=false;signout.disabled=false}});
  async function isSignedIn(){const {data,error}=await client.auth.getUser();return !error&&data.user?.id===user.id}
  async function showProfile(){if(!await isSignedIn()){details.hidden=true;profileFields.disabled=true;location.replace('sign-in.html');return}details.hidden=false;document.body.classList.add('account-ready');summary.append(signout);const navigation=document.querySelector('.nav-sign-in');navigation.textContent='My account';navigation.href='account.html';navigation.setAttribute('aria-current','page');document.getElementById('auth-title').textContent='Your profile';document.querySelector('.auth-lead').textContent='Manage your personal details and keep your account up to date.';document.getElementById('account-email').textContent=user.email||'';clear();const {data,error}=await client.from('customer_profiles').select('date_of_birth,phone,gender,country,address').eq('id',user.id).maybeSingle();if(error){say('Your profile could not be loaded. Please try again later.',true);return}if(data)for(const key of ['date_of_birth','phone','gender','country','address'])profile.elements[key].value=data[key]||'';restoreDob();profileFields.disabled=false}
  profile.addEventListener('submit',async event=>{event.preventDefault();if(busy||profileFields.disabled||!profile.reportValidity())return;busy=true;profileFields.disabled=true;clear();const saved=document.getElementById('profile-status');saved.textContent='';try{if(!await isSignedIn()){details.hidden=true;location.replace('sign-in.html');return}const values=Object.fromEntries(['date_of_birth','phone','gender','country','address'].map(key=>[key,profile.elements[key].value.trim()]));if(!countryCodes.includes(values.country)||!/^\d{4}-\d{2}-\d{2}$/.test(values.date_of_birth)||values.date_of_birth< '1900-01-01'||values.date_of_birth>profile.elements.date_of_birth.max)throw Error('Invalid profile');const {error}=await client.from('customer_profiles').upsert({id:user.id,...values,address:values.address||null},{onConflict:'id'});if(error)throw error;saved.textContent='Your details have been saved.'}catch{say('Your details could not be saved. Please try again later.',true)}finally{busy=false;if(!details.hidden)profileFields.disabled=false}});
  const {data:listener}=client.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){details.hidden=true;profileFields.disabled=true;profile.reset();profile.elements.date_of_birth.value="";}});
  window.addEventListener('pagehide',()=>{details.hidden=true;profileFields.disabled=true;profile.reset();profile.elements.date_of_birth.value="";document.getElementById('account-email').textContent='';listener.subscription.unsubscribe();document.removeEventListener('compasslanguagechange',localizeCountries)},{once:true});
  window.addEventListener('pageshow',event=>{if(event.persisted)location.reload()});
  await showProfile();
};
