(()=>{'use strict';const mode=document.body.dataset.authPage;if(!mode)return;const form=document.getElementById('auth-form'),fields=document.getElementById('auth-fields'),status=document.getElementById('auth-status'),errorNode=document.getElementById('auth-error'),details=document.getElementById('account-details');let client,busy=false;
function message(text,error=false){const target=error?errorNode:status;target.textContent=text;if(error)target.focus()}
function clearMessages(){status.textContent='';errorNode.textContent=''}
// Share only short-lived PKCE verifiers between tabs; sessions remain tab-local.
const authStorage={getItem(key){if(!(key.startsWith('cape-compass-auth-')&&key.endsWith('code-verifier')))return sessionStorage.getItem(key);try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Date.now()-saved.created<86400000)return saved.value;localStorage.removeItem(key)}catch{}return sessionStorage.getItem(key)},setItem(key,value){if((key.startsWith('cape-compass-auth-')&&key.endsWith('code-verifier'))){try{localStorage.setItem(key,JSON.stringify({value,created:Date.now()}));return}catch{}}sessionStorage.setItem(key,value)},removeItem(key){sessionStorage.removeItem(key);if((key.startsWith('cape-compass-auth-')&&key.endsWith('code-verifier')))try{localStorage.removeItem(key)}catch{}}};
if(mode==='sign-in'&&fields){const resend=document.createElement('button');resend.type='button';resend.className='text-link';resend.textContent='Resend confirmation email';fields.append(resend);resend.addEventListener('click',async()=>{if(!client||busy)return;const input=form.elements.email;if(!input.reportValidity())return;clearMessages();setBusy(true);try{const {error}=await client.auth.resend({type:'signup',email:input.value.trim(),options:{emailRedirectTo:accountUrl()}});if(error)throw error;message('If your account needs confirmation, a fresh email has been sent. Use only the newest link.')}catch(error){message(friendly(error),true)}finally{setBusy(false)}})}
function setBusy(value){busy=value;if(form){form.setAttribute('aria-busy',String(value));fields.disabled=value}const signout=document.getElementById('sign-out');if(signout)signout.disabled=value}
function redirectUrl(page){const local=['127.0.0.1','localhost'].includes(location.hostname);return new URL(page+(local?'.html':''),local?location.href:'https://cape-coast-compass.pages.dev/').href}function accountUrl(){return redirectUrl('account')}function resetUrl(){return redirectUrl('update-password')}
function isPublicKey(key){if(typeof key!=='string')return false;if(/^sb_publishable_[A-Za-z0-9_-]+$/.test(key))return true;try{return JSON.parse(atob(key.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role==='anon'}catch{return false}}
function friendly(error){const code=error?.code;if(code==='invalid_credentials')return 'The email or password is incorrect. Please try again.';if(code==='email_not_confirmed')return 'Please confirm your email before signing in.';if(code==='weak_password')return 'Choose a stronger password with at least 10 characters.';if(['over_request_rate_limit','over_email_send_rate_limit'].includes(code))return 'Too many attempts. Please wait a few minutes and try again.';if(code==='signup_disabled')return 'Account registration is temporarily unavailable.';return 'We could not complete that request. Please try again.'}
for(const button of document.querySelectorAll('[data-password-toggle]'))button.addEventListener('click',()=>{const input=document.getElementById(button.dataset.passwordToggle),show=input.type==='password';input.type=show?'text':'password';button.setAttribute('aria-pressed',String(show));button.setAttribute('aria-label',show?'Hide password':'Show password');button.textContent=show?'Hide':'Show'});
if(form)form.addEventListener('submit',async event=>{event.preventDefault();if(!client||busy||!form.reportValidity())return;clearMessages();const email=form.elements.email?.value.trim(),password=form.elements.password?.value,confirmation=form.elements.confirm?.value;if(confirmation!==undefined&&confirmation!==password){message('Your passwords do not match.',true);form.elements.confirm.focus();return}setBusy(true);try{if(mode==='sign-in'){const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;if(!data.session)throw Error('Session unavailable');location.assign(accountUrl());return}
if(mode==='create-account'){const {data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:accountUrl(),data:{terms_accepted_at:new Date().toISOString(),terms_version:'2026-10-02'}}});if(error)throw error;form.elements.password.value='';form.elements.confirm.value='';if(data.session){location.assign(accountUrl());return}message('Check your inbox for a confirmation link. If this email already has an account, sign in or reset your password.');return}
if(mode==='forgot-password'){const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:resetUrl()});if(error)throw error;message('If an account exists for this email, a password reset link has been sent. Use only the newest link.');return}
if(mode==='update-password'){const {error}=await client.auth.updateUser({password});if(error)throw error;form.reset();fields.hidden=true;message('Your password has been updated. You can return to your account.');const link=document.createElement('a');link.href='account.html';link.className='button';link.textContent='My account';status.after(link);return}}
catch(error){message(friendly(error),true)}finally{setBusy(false)}});
async function initialize(){try{const callback=new URL(location.href),fragment=new URLSearchParams(callback.hash.slice(1)),callbackError=callback.searchParams.has('error')||fragment.has('error'),hasCallback=callbackError||callback.searchParams.has('code')||callback.searchParams.has('token_hash')||fragment.has('access_token')||fragment.has('refresh_token');
let recoveryCallback=fragment.get('type')==='recovery'||callback.searchParams.get('type')==='recovery';
if(hasCallback)history.replaceState(null,'',location.pathname);
const response=await fetch('auth-config.json',{cache:'no-store'});if(!response.ok)throw Error('Configuration unavailable');const config=await response.json();let url;try{url=new URL(config.url)}catch{}if(!url||url.protocol!=='https:'||url.username||url.password||!isPublicKey(config.publishableKey)){message('Account sign-in is not available yet. Please check back soon.');return}
try{const test='cape-compass-storage-check';sessionStorage.setItem(test,'1');sessionStorage.removeItem(test)}catch{message('Allow browser session storage to sign in. Your password will not be saved.');return}
const {createClient}=await import('./assets/vendor/supabase-auth.js');client=createClient(url.origin,config.publishableKey,{auth:{storage:authStorage,storageKey:'cape-compass-auth',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,flowType:'implicit'}});
function recoverLink(){const recovery=mode==='update-password'||fragment.get('type')==='recovery'||callback.searchParams.get('type')==='recovery';location.replace((recovery?'forgot-password.html':'sign-in.html')+'?notice='+(recovery?'recovery-link':'confirmation-link'))}
if(callbackError){recoverLink();return}
if(hasCallback){try{let result;if(callback.searchParams.has('code')){const flowId=callback.searchParams.get('sb_flow_id'),key=flowId&&/^[A-Za-z0-9_-]+$/.test(flowId)?'cape-compass-auth-flow-'+flowId+'-code-verifier':'cape-compass-auth-code-verifier';if(!authStorage.getItem(key)){recoverLink();return}result=await client.auth.exchangeCodeForSession(callback.searchParams.get('code'),flowId?{flowId}:undefined)}else if(callback.searchParams.has('token_hash')){const type=callback.searchParams.get('type');if(!['email','signup','recovery'].includes(type)){recoverLink();return}result=await client.auth.verifyOtp({token_hash:callback.searchParams.get('token_hash'),type})}else{const access_token=fragment.get('access_token'),refresh_token=fragment.get('refresh_token');if(!access_token||!refresh_token){recoverLink();return}result=await client.auth.setSession({access_token,refresh_token})}if(result.error||!result.data.session){recoverLink();return}if(result.data.redirectType==='PASSWORD_RECOVERY')recoveryCallback=true}catch{recoverLink();return}}
client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'&&mode==='account')location.replace('sign-in.html')});
const {data:{session},error}=await client.auth.getSession();if(error)throw error;let user=null;if(session){const result=await client.auth.getUser();if(!result.error)user=result.data.user;else await client.auth.signOut({scope:'local'})}
if(hasCallback&&!user){recoverLink();return}
if(hasCallback&&recoveryCallback&&mode!=='update-password'){location.replace(resetUrl());return}
if(mode==='account'){if(!user){location.replace('sign-in.html');return}if(typeof window.CapeCompassAccount!=='function')throw Error('Account module unavailable');await window.CapeCompassAccount(client,user);return}
if(mode==='update-password'&&!user){message('This password reset link is invalid or has expired. Request a new link.');return}
const notice=callback.searchParams.get('notice');if(user&&(mode==='sign-in'||mode==='create-account')&&!notice){location.replace('account.html');return}
clearMessages();fields.disabled=false;
if(notice){history.replaceState(null,'',location.pathname);if(notice==='confirmation-link')message('Continue with your email and password to finish signing in. If your email still needs confirmation, select Resend confirmation email.');if(notice==='recovery-link')message('This reset link is invalid or expired. Enter your email to request a new link.');}
if(mode==='create-account')message('We’ll email you a confirmation link to finish creating your account.');
}catch{message('The account service is unavailable right now. Please try again later.');}}
initialize();
})();
