(()=>{'use strict';
const root=document.querySelector('.regional-directory');if(!root)return;
const mount=document.getElementById('cape-destination-mount'),browser=document.getElementById('region-browser'),tools=root.querySelector('.region-tools'),originalHeading=root.querySelector('.page-heading'),emptyMount=document.getElementById('region-empty-mount');
const essentialIds=['cape-coast-castle-museum','fort-william-lighthouse','fort-victoria','kotokuraba-market','emintsimadze-palace','fosu-lagoon'];let active=false,grid;
const search=document.getElementById('region-search'),reset=document.getElementById('region-reset'),labels=['region-select','town-select','region-category'].map(id=>document.getElementById(id).closest('label')),searchLabel=search.closest('label'),searchText=searchLabel.firstChild,originalSearchText=searchText.textContent,originalPlaceholder=search.placeholder;
const movable=[tools,document.getElementById('region-results'),root.querySelector('.card-trip-links'),emptyMount,document.getElementById('town-map-mount'),document.getElementById('town-list-panel')];const anchors=movable.map(e=>{const anchor=document.createComment('directory control position');e.before(anchor);return anchor});let interestControls;
const node=(tag,text,className)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(className)e.className=className;return e};
function interests(){for(const button of browser.querySelectorAll('[data-cape-interest]'))button.setAttribute('aria-pressed',String(button.dataset.capeInterest===document.getElementById('region-category').value));reset.hidden=active&&!Boolean(search.value.trim()||document.getElementById('region-category').value)}
function build(records,town){
 const section=node('section',null,'cape-destination');section.setAttribute('aria-labelledby','cape-destination-heading');const hero=node('div',null,'cape-hero'),copy=node('div',null,'cape-hero-copy'),heading=node('h1','Discover Cape Coast');heading.id='cape-destination-heading';const subtitle=node('p','Where Ghana’s history meets the Atlantic.','cape-subtitle'),intro=node('p','Explore Cape Coast’s castle and hilltop forts, discover Fante culture through traditional leadership and Asafo heritage, and experience the markets, lagoon and Atlantic coastline that shape everyday life.','cape-introduction');
 const actions=node('div',null,'cape-actions'),map=node('button','View map','button');map.type='button';map.id='cape-view-map';map.setAttribute('aria-controls','town-map-panel');map.addEventListener('click',()=>{const button=document.getElementById('town-view-map');if(!button)return;button.click();document.getElementById('town-map-panel').scrollIntoView({behavior:'smooth',block:'start'})});const trip=node('a','Build a Cape Coast trip','text-link');trip.id='cape-build-trip';trip.href='/my-trip';actions.append(map,trip);copy.append(heading,subtitle,intro,actions);hero.append(copy);
 const photo=records.get('cape-coast-castle-museum')?.photos?.find(p=>p.src&&!p.src.includes('placeholder'));if(photo){const figure=node('figure',null,'cape-hero-photo'),img=node('img');img.src=photo.src;if(photo.srcset)img.srcset=photo.srcset;img.sizes='(max-width:767px) calc(100vw - 40px), 50vw';img.width=photo.width;img.height=photo.height;img.alt=photo.caption||'Cape Coast Castle courtyard and main building';const credit=node('figcaption',photo.credit||'','cape-photo-credit');if(photo.changes)credit.append(node('span',photo.changes.split('Download')[0].trim()));if(photo.source?.startsWith('https://')){const source=node('a','Photo source');source.href=photo.source;source.target='_blank';source.rel='noopener noreferrer';credit.append(source)}figure.append(img,credit);hero.append(figure)}
 const essentials=node('section',null,'cape-essentials');essentials.setAttribute('aria-labelledby','cape-essentials-heading');const essentialsHeading=node('h2','Cape Coast essentials');essentialsHeading.id='cape-essentials-heading';const note=node('p','Six places to begin exploring Cape Coast.','cape-section-note');grid=node('div',null,'cape-essential-links');grid.id='cape-essential-grid';essentials.append(essentialsHeading,note,grid);
 const buttons=node('div',null,'cape-interest-controls');interestControls=buttons;buttons.setAttribute('role','group');buttons.setAttribute('aria-label','Explore Cape Coast by interest');const supported=new Set(town.sites.map(s=>records.get(s.id)?.category));for(const option of [...document.getElementById('region-category').options].sort((a,b)=>['','Heritage','Culture & everyday life','Faith & architecture','Nature & coast'].indexOf(a.value)-['','Heritage','Culture & everyday life','Faith & architecture','Nature & coast'].indexOf(b.value))){if(option.value&&!supported.has(option.value))continue;const button=node('button',option.value||'All interests');button.type='button';button.dataset.capeInterest=option.value;button.addEventListener('click',()=>{const select=document.getElementById('region-category');select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}))});buttons.append(button)}section.append(hero,essentials);mount.append(section)
}
window.CompassCapeCoast={update({region,town,records}){active=region?.id==='central-region'&&town?.id==='cape-coast';root.classList.toggle('cape-destination-active',active);originalHeading.hidden=active;if(active){if(!mount.childElementCount)build(records,town);if(tools.parentElement!==browser){anchors[0].before(browser);browser.append(tools,interestControls,...movable.slice(1));}labels.forEach(e=>e.hidden=true);searchText.textContent='Search within Cape Coast';search.placeholder='Search Cape Coast attractions';reset.textContent='Clear filters';interests()}else{mount.replaceChildren();grid=null;interestControls?.remove();interestControls=null;movable.forEach((e,i)=>{if(e.previousSibling!==anchors[i])anchors[i].after(e)});labels.forEach(e=>e.hidden=false);searchText.textContent=originalSearchText;search.placeholder=originalPlaceholder;reset.textContent='Reset filters';reset.hidden=false;if(browser.previousSibling!==emptyMount)emptyMount.after(browser)}},cards(cards){if(!active||!grid)return;const byId=new Map(cards.map(card=>[card.querySelector('.attraction-view').getAttribute('href').match(/places\/(.+)\.html/)[1],card]));grid.replaceChildren(...essentialIds.map(id=>{const card=byId.get(id);if(!card)return null;const a=node('a',null,'cape-essential-link');a.href=card.querySelector('.attraction-view').getAttribute('href');const img=card.querySelector('.attraction-media img')?.cloneNode(true);if(img){img.sizes='(max-width:767px) 150px, 100px';a.append(img)}a.append(node('span',card.querySelector('h3').textContent));const credit=card.querySelector('.attraction-photo-credits')?.cloneNode(true),item=node('div',null,'cape-essential-item');item.append(a);if(credit)item.append(credit);return item}).filter(Boolean))},scrollResults(){if(active)browser.scrollIntoView({behavior:'smooth',block:'start'})}};
})();
