(async()=>{'use strict';const regionGrid=document.getElementById('home-regions');if(!regionGrid)return;
const node=(tag,text,className)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(className)e.className=className;return e};
try{const [r,a]=await Promise.all([fetch('regions-data.json'),fetch('attractions.json')]);if(!r.ok||!a.ok)throw Error('Catalogue unavailable');const data=await r.json(),records=new Map([...(await a.json()),...data.newSites].map(p=>[p.id,p])),regions=data.regions;
const towns=regions.flatMap(region=>region.towns.map(town=>({region,town}))),total=new Set(towns.flatMap(({town})=>town.sites.map(s=>s.id))).size;document.getElementById('home-catalogue-count').textContent=`${total} attractions · ${towns.length} destinations · ${regions.length} regions represented`;
for(const region of regions){const count=new Set(region.towns.flatMap(t=>t.sites.map(s=>s.id))).size,link=node('a',null,'region-choice');link.href='attractions.html?region='+region.id.replace(/-region$/,'');link.append(node('h3',region.name),node('p',`${region.towns.length} ${region.towns.length===1?'town/destination':'towns/destinations'} · ${count} ${count===1?'attraction':'attractions'}`));regionGrid.append(link)}
const features=[['central-region','cape-coast','cape-coast-castle-museum'],['ashanti-region','kumasi','kumasi-manhyia-palace-museum'],['greater-accra-region','accra','accra-independence-square'],['eastern-region','aburi','aburi-historic-colonial-era-botanical-gardens'],['savannah-region','larabanga','larabanga-larabanga-mosque']];
const grid=document.getElementById('home-destinations');for(const [regionId,townId,placeId]of features){const pair=towns.find(p=>p.region.id===regionId&&p.town.id===townId),place=records.get(placeId),photo=place?.photos?.find(p=>p.src&&!p.src.includes('placeholder'));if(!pair||!photo)continue;const card=node('article',null,'ghana-destination'),link=node('a',null,'ghana-destination-link');link.href=`attractions.html?region=${regionId.replace(/-region$/,'')}&town=${townId}`;const img=node('img');img.src=photo.src;img.srcset=photo.srcset||'';img.sizes='(max-width:767px) calc(100vw - 40px), 30vw';img.width=photo.width;img.height=photo.height;img.loading='lazy';img.alt=photo.caption||place.name;link.append(img,node('p',pair.region.name,'eyebrow'),node('h3',pair.town.name),node('p',place.name,'helper'));const credit=node('p',null,'ghana-photo-credit');credit.append(document.createTextNode('Photo: '));if(/^https:\/\//.test(photo.source||'')){const source=node('a',photo.credit||'Photo source');source.href=photo.source;source.target='_blank';source.rel='noopener noreferrer';credit.append(source)}else credit.append(document.createTextNode(photo.credit||''));if(photo.license){credit.append(document.createTextNode(' · '));const license=node('a',photo.license);license.href=photo.licenseUrl;license.target='_blank';license.rel='noopener noreferrer';credit.append(license)}if(photo.changes)credit.append(node('span',photo.changes.split('Download')[0].trim()));card.append(link,credit);grid.append(card)}
regionGrid.dataset.ready='true';document.dispatchEvent(new Event('compasshomecontentready'));
}catch{document.getElementById('home-catalogue-count').textContent='Explore the current catalogue by region.';const link=node('a','Explore regions','text-link');link.href='attractions.html';regionGrid.append(link)}})();
