(()=>{'use strict';
const control=document.querySelector('[data-language-switcher]');if(!control)return;
const toggle=control.querySelector('.language-toggle'),menu=control.querySelector('.language-menu'),options=[...menu.querySelectorAll('[data-language]')],status=control.querySelector('.language-status'),script=document.currentScript,base=new URL('.',script.src),storageKey='cape-compass-language',names={en:'English',fr:'Français',es:'Español',de:'Deutsch'},cache={en:{}},originalText=new WeakMap(),originalAttrs=new WeakMap();const announcement=document.createElement('p');announcement.className='language-announcement';announcement.setAttribute('role','status');announcement.setAttribute('aria-live','polite');control.append(announcement);let language='en',dictionary={},requestId=0,observer;const originalTitle=document.title;
const normalize=s=>s.trim().replace(/\s+/g,' ');
function translate(source){const text=normalize(source);let translated=dictionary[text];if(translated)return translated;
let match;if((match=text.match(/^(\d+) (town\/destination|towns\/destinations) · (\d+) (attraction|attractions)$/))){const towns=dictionary[Number(match[1])===1?"{count} town/destination":"{count} towns/destinations"],places=dictionary[Number(match[3])===1?"{count} attraction":"{count} attractions"];if(towns&&places)return towns.replace("{count}",match[1])+" · "+places.replace("{count}",match[3])}if((match=text.match(/^(\d+) attractions · (\d+) destinations · (\d+) regions represented$/))){const template=dictionary['{attractions} attractions · {towns} destinations · {regions} regions represented'];if(template)return template.replace('{attractions}',match[1]).replace('{towns}',match[2]).replace('{regions}',match[3])}if((match=text.match(/^(\d+) city (place|places)$/))){const template=dictionary['{count} city '+match[2]];if(template)return template.replace('{count}',match[1])}
if((match=text.match(/^Photo (\d+) of (\d+)\. Supplied by the site owner; photographer not provided\. Color and brightness refined with AI\. 8K file is upscaled\.$/))){const template=dictionary['Photo {current} of {total}. Supplied by the site owner; photographer not provided. Color and brightness refined with AI. 8K file is upscaled.'];if(template)return template.replace('{current}',match[1]).replace('{total}',match[2])}
if((match=text.match(/^Estimated accuracy: (\d+) metres\. Edit this to an agreed landmark if needed\. Location entry does not arrange transport\.$/))){const template=dictionary['Estimated accuracy: {accuracy} metres. Edit this to an agreed landmark if needed. Location entry does not arrange transport.'];if(template)return template.replace('{accuracy}',match[1])}
if(text.startsWith("View photo: ")&&dictionary["View photo: {caption}"])return dictionary["View photo: {caption}"].replace("{caption}",translate(text.slice(12)));if(text.endsWith(" photo gallery")&&dictionary["{place} photo gallery"])return dictionary["{place} photo gallery"].replace("{place}",translate(text.slice(0,-14)));if(text.startsWith("Explore ")&&dictionary["Explore {place}"])return dictionary["Explore {place}"].replace("{place}",translate(text.slice(8)));return text;
}
function excluded(element){return !element||element.closest('script,style,textarea,[data-language-switcher],.notranslate,[translate="no"]')}
function observe(){observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['alt','aria-label','placeholder','title']})}
function apply(){observer.disconnect();const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){if(excluded(node.parentElement)||!normalize(node.nodeValue))continue;let source=originalText.get(node);if(source===undefined){source=node.nodeValue;originalText.set(node,source)}const value=language==='en'?source:source.replace(/\S[\s\S]*\S|\S/,()=>translate(source));if(node.nodeValue!==value)node.nodeValue=value}
for(const element of document.querySelectorAll('[alt],[aria-label],[placeholder],[title]')){if(excluded(element))continue;let attrs=originalAttrs.get(element);if(!attrs){attrs={};originalAttrs.set(element,attrs)}for(const attribute of ['alt','aria-label','placeholder','title']){if(!element.hasAttribute(attribute))continue;if(!(attribute in attrs))attrs[attribute]=element.getAttribute(attribute);const source=attrs[attribute],value=language==='en'?source:translate(source);if(element.getAttribute(attribute)!==value)element.setAttribute(attribute,value)}}
document.title=language==='en'?originalTitle:translate(originalTitle);for(const meta of document.querySelectorAll('meta[name=description],meta[property="og:description"],meta[name="twitter:description"],meta[property="og:title"],meta[name="twitter:title"]')){let attrs=originalAttrs.get(meta);if(!attrs){attrs={content:meta.content};originalAttrs.set(meta,attrs)}meta.content=language==='en'?attrs.content:translate(attrs.content)}document.documentElement.lang=language;menu.querySelector('p').textContent=translate('Choose your language');toggle.setAttribute('aria-label',translate('Choose language')+' · '+names[language]);toggle.querySelector('img').src=new URL('assets/flags/'+language+'.svg',base).href;toggle.querySelector('[data-language-code]').textContent=language.toUpperCase();for(const option of options)option.setAttribute('aria-pressed',String(option.dataset.language===language));observe();}
observer=new MutationObserver(records=>{let relevant=false;for(const record of records){const element=record.target.nodeType===Node.TEXT_NODE?record.target.parentElement:record.target;if(excluded(element))continue;relevant=true;if(record.type==='characterData')originalText.delete(record.target);if(record.type==='attributes'){const attrs=originalAttrs.get(record.target);if(attrs)delete attrs[record.attributeName]}}if(relevant)apply()});
function close(focus=false){menu.hidden=true;toggle.setAttribute('aria-expanded','false');if(focus)toggle.focus()}
function open(focus=false){menu.hidden=false;toggle.setAttribute('aria-expanded','true');if(focus)(options.find(option=>option.dataset.language===language)||options[0]).focus()}
async function select(code,{persist=true,announce=true}={}){if(!names[code])return;const id=++requestId;control.setAttribute('aria-busy','true');status.textContent='';try{if(!cache[code]){const response=await fetch(new URL('assets/languages/'+code+'.json?v=20261007-ghana-wording-1',base));if(!response.ok)throw Error('Language unavailable');cache[code]=await response.json()}if(id!==requestId)return;language=code;dictionary=cache[code];apply();if(persist)try{localStorage.setItem(storageKey,code)}catch{}if(announce){announcement.textContent=translate('Language changed to {language}.').replace('{language}',names[code]);close(true)}document.dispatchEvent(new CustomEvent('compasslanguagechange',{detail:{language:code}}));}catch{if(id===requestId){status.textContent=translate('Language could not be loaded. Please try again.');open()}}finally{if(id===requestId)control.removeAttribute('aria-busy')}}
toggle.addEventListener('click',()=>menu.hidden?open():close());toggle.addEventListener('keydown',event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();open(true)}});options.forEach(option=>option.addEventListener('click',()=>select(option.dataset.language)));menu.addEventListener('keydown',event=>{const index=options.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?options.length-1:(index+(event.key==='ArrowDown'?1:-1)+options.length)%options.length;options[next].focus()}});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!menu.hidden){event.preventDefault();close(true)}});document.addEventListener('click',event=>{if(!control.contains(event.target))close()});control.addEventListener('focusout',event=>{if(event.relatedTarget&&!control.contains(event.relatedTarget))close()});
window.CompassI18n={t:translate,get language(){return language}};observe();let saved='en';try{saved=localStorage.getItem(storageKey)||'en'}catch{}if(names[saved]&&saved!=='en')select(saved,{persist:false,announce:false});else apply();
})();
