(async()=>{'use strict';
const root=document.querySelector('.regional-directory');if(!root)return;
const byId=id=>document.getElementById(id),search=byId('region-search'),regionSelect=byId('region-select'),townSelect=byId('town-select'),category=byId('region-category'),container=root.querySelector('.region-groups'),heading=byId('region-browser-heading'),description=byId('region-browser-description'),choices=byId('region-browser-choices'),breadcrumb=byId('region-breadcrumb'),result=byId('region-results'),empty=document.createElement('div');
empty.id='region-empty';empty.className='note';empty.innerHTML="<h2>No places found.</h2><p>Try another search or reset your filters.</p>";const emptyMount=byId('region-empty-mount');
const normal=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,'');
const counts={en:n=>`${n} ${n===1?'attraction':'attractions'} found`,fr:n=>`${n} attractions trouvées`,es:n=>`${n} atracciones encontradas`,de:n=>`${n} Sehenswürdigkeiten gefunden`};
// Navigation uses the existing dataset. Card markup is fetched only for a selected town.
let regions=[],records=new Map(),generation=0;const fragments=new Map();
function selected(){const region=regions.find(r=>r.id===regionSelect.value);return {region,town:region?.towns.find(t=>region.id+'-'+t.id===townSelect.value)}}
function urlFor(region,town,filters=true){const url=new URL(location.href);url.hash='';for(const key of ['region','town','q','category'])url.searchParams.delete(key);if(region)url.searchParams.set('region',region.id.replace(/-region$/,''));if(town)url.searchParams.set('town',town.id);if(filters&&search.value.trim())url.searchParams.set('q',search.value.trim());if(filters&&category.value)url.searchParams.set('category',category.value);return url}
function syncOptions(){for(const option of townSelect.options)option.hidden=Boolean(option.value&&regionSelect.value&&option.dataset.region!==regionSelect.value)}
function navigate(region,town){regionSelect.value=region?.id||'';townSelect.value=town?region.id+'-'+town.id:'';search.value='';category.value='';syncOptions();history.pushState(null,'',urlFor(region,town,false));render();heading.focus()}
function link(label,region,town,current=false){const element=document.createElement(current?'span':'a');element.textContent=label;if(current)element.setAttribute('aria-current','page');else{element.href=urlFor(region,town,false);element.addEventListener('click',event=>{if(event.button||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();navigate(region,town)})}return element}
function choice(label,detail,region,town){const a=link('',region,town);a.className='region-choice';const name=document.createElement('h3'),count=document.createElement('p');name.textContent=label;count.textContent=detail;a.append(name,count);return a}
function siteMatches(site,region,town){const record=records.get(site.id),term=normal(search.value.trim());return (!category.value||record?.category===category.value)&&normal([site.label,record?.name,record?.description,region.name,town.name].join(' ')).includes(term)}
function updateEmptyState(matchCount){const active=Boolean(search.value.trim()||category.value);const showEmptyState=active&&matchCount===0;emptyMount.replaceChildren(...(showEmptyState?[empty]:[]))}
function eligible(town,region){return town.sites.some(site=>siteMatches(site,region,town))}
function renderRegionCards(){for(const region of regions){if(region.towns.some(t=>eligible(t,region))){const n=new Set(region.towns.flatMap(t=>t.sites.map(s=>s.id))).size;choices.append(choice(region.name,region.towns.length+' towns/destinations · '+n+' attractions',region,null))}}}
function renderTownCards(region){for(const town of region.towns){if(eligible(town,region)){const n=new Set(town.sites.map(s=>s.id)).size;choices.append(choice(town.name,n+' '+(n===1?'listing':'listings'),region,town))}}}
async function renderAttractionCards(region,town,version){const id=region.id+'-'+town.id;let html=fragments.get(id);if(!html){const response=await fetch('assets/directory/'+id+'.html?v='+(root.dataset.cardVersion||''));if(!response.ok)throw Error('Town cards unavailable');html=await response.text();fragments.set(id,html)}if(version!==generation)return;const template=document.createElement('template');template.innerHTML=html;const section=template.content.querySelector('.town-group'),grid=section.querySelector('.directory-grid'),cards=[...grid.querySelectorAll('.place-card')].filter(card=>(!category.value||card.dataset.category===category.value)&&normal([card.dataset.search,card.textContent,card.dataset.region,card.dataset.town].join(' ')).includes(normal(search.value.trim())));grid.replaceChildren(...cards);for(const card of cards)card.hidden=false;section.hidden=false;if(cards.length){const group=document.createElement('div');group.className='region-content';group.append(section);container.append(group)}result.textContent=(counts[document.documentElement.lang]||counts.en)(cards.length);updateEmptyState(cards.length);window.CompassTownMap?.update({region,town,places:cards.map(card=>records.get(card.querySelector('.attraction-view').getAttribute('href').match(/places\/(.+)\.html/)[1])).filter(Boolean)})}
async function render(){const version=++generation,{region,town}=selected(),direct=Boolean(region&&town);root.dataset.rendering='true';if(!direct)window.CompassTownMap?.update(null);else window.CompassTownMap?.loading();root.dataset.browseMode=direct?'attractions':region?'towns':'regions';root.dataset.selectedTown=direct?'true':'false';container.replaceChildren();choices.replaceChildren();breadcrumb.replaceChildren();breadcrumb.hidden=!region;breadcrumb.append(link('Explore Ghana',null,null,!region));if(region){breadcrumb.append(document.createTextNode(' → '),link(region.name,region,null,!town));if(town)breadcrumb.append(document.createTextNode(' → '),link(town.name,region,town,true))}heading.textContent=town?town.name:region?region.name:'Choose a region';description.hidden=!region||direct;description.textContent=region?`Explore the historic towns and heritage destinations of Ghana’s ${region.name}.`:'';choices.hidden=direct;container.hidden=!direct;emptyMount.replaceChildren();result.setAttribute('translate','no');
if(!region){renderRegionCards();result.textContent=choices.childElementCount+' regions';updateEmptyState(choices.childElementCount)}
else if(!town){renderTownCards(region);result.textContent=choices.childElementCount+' towns/destinations';updateEmptyState(choices.childElementCount)}
else{result.textContent='';try{await renderAttractionCards(region,town,version)}catch{if(version===generation){result.textContent='The attraction cards could not be loaded. Please try again.'}}}if(version===generation)root.dataset.rendering='false';}
function changed(push=false){syncOptions();const {region,town}=selected();history[push?'pushState':'replaceState'](null,'',urlFor(region,town));render()}
function restore(){const params=new URL(location.href).searchParams,region=regions.find(r=>r.id===params.get('region')||r.id.replace(/-region$/,'')===params.get('region'));regionSelect.value=region?.id||'';const town=region?.towns.find(t=>t.id===params.get('town')||region.id+'-'+t.id===params.get('town'));townSelect.value=town?region.id+'-'+town.id:'';search.value=params.get('q')||'';category.value=params.get('category')||'';if(!params.has('region')&&location.hash){let hash='';try{hash=decodeURIComponent(location.hash.slice(1))}catch{}for(const r of regions){const t=r.towns.find(t=>r.id+'-'+t.id===hash);if(r.id===hash||t){regionSelect.value=r.id;townSelect.value=t?r.id+'-'+t.id:'';break}}}syncOptions();return render()}
try{const [regionResponse,recordResponse]=await Promise.all([fetch('regions-data.json'),fetch('attractions.json')]);if(!regionResponse.ok||!recordResponse.ok)throw Error('Data unavailable');const data=await regionResponse.json(),existing=await recordResponse.json();regions=data.regions;records=new Map([...existing,...data.newSites].map(s=>[s.id,s]));}catch{result.textContent='The regions could not be loaded. Please refresh the page.';return}
search.addEventListener('input',()=>changed());category.addEventListener('change',()=>changed(true));regionSelect.addEventListener('change',()=>{if(townSelect.selectedOptions[0]?.dataset.region!==regionSelect.value)townSelect.value='';changed(true)});townSelect.addEventListener('change',()=>{if(townSelect.value)regionSelect.value=townSelect.selectedOptions[0].dataset.region;changed(true)});byId('region-reset').addEventListener('click',()=>{navigate(null,null);search.focus()});document.addEventListener('compasslanguagechange',render);window.addEventListener('popstate',restore);window.addEventListener('hashchange',restore);await restore();root.dataset.browseReady='true';
})();
