(()=>{'use strict';
const root=document.querySelector('.regional-directory');if(!root)return;
const mount=document.getElementById('town-map-mount'),template=document.getElementById('town-map-template'),ui=template.content.cloneNode(true),byId=id=>ui.querySelector('#'+id);
const controls=byId('town-view-controls'),listButton=byId('town-view-list'),mapButton=byId('town-view-map'),panel=byId('town-map-panel'),canvas=byId('town-map-canvas'),empty=byId('town-map-empty'),summary=byId('town-map-summary'),list=root.querySelector('.region-groups');
let view='list',current=null,map=null,layers=null,version=0,library,townKey='';
// Accept only explicit, sourced verification on the attraction itself, never photo GPS or town centres.
function verifiedLocation(record){const p=record?.location;if(!p||p.verified!==true||typeof p.source!=='string'||!/^https:\/\//.test(p.source))return null;const {latitude,longitude}=p;if(typeof latitude!=='number'||typeof longitude!=='number'||!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude)>90||Math.abs(longitude)>180)return null;return [latitude,longitude]}
function clearMap(){if(map){map.remove();map=null;layers=null}canvas.replaceChildren();canvas.hidden=true;canvas.dataset.markerCount='0'}
function leaflet(){if(library)return library;library=new Promise((resolve,reject)=>{let loaded=0;const ready=()=>{if(++loaded===2)resolve(window.L)},failed=()=>{library=null;reject(Error('Map library unavailable'))};const css=document.createElement('link');css.rel='stylesheet';css.href='assets/vendor/leaflet/leaflet.css';css.onload=ready;css.onerror=failed;document.head.append(css);const script=document.createElement('script');script.src='assets/vendor/leaflet/leaflet.js';script.onload=ready;script.onerror=failed;document.head.append(script)});return library}
function popup(place,town,region){const box=document.createElement('div');box.className='town-marker-popup';const name=document.createElement('h3');name.textContent=place.name;box.append(name);if(place.category){const category=document.createElement('p');category.textContent=place.category;box.append(category)}const location=document.createElement('p');location.textContent=town.name+', '+region.name;const a=document.createElement('a');a.className='button';a.textContent='View place';a.href='places/'+place.id+'.html';a.setAttribute('aria-label','View '+place.name);box.append(location);if(place.location.label){const detail=document.createElement('p');detail.textContent='Mapped location: '+place.location.label;box.append(detail)}box.append(a);const source=document.createElement('a');source.textContent='Location source';source.href=place.location.source;source.target='_blank';source.rel='noopener noreferrer';source.className='town-location-source';box.append(source);return box}
function hasSelectedTown(){return Boolean(current?.region?.id&&current?.town?.id&&document.getElementById('region-select').value===current.region.id&&document.getElementById('town-select').value===current.region.id+'-'+current.town.id)}
async function render(){const ticket=++version;empty.hidden=true;if(!hasSelectedTown()){controls.hidden=true;panel.hidden=true;mount.replaceChildren();clearMap();return}if(!controls.isConnected)mount.append(controls,panel);controls.hidden=false;listButton.setAttribute('aria-pressed',String(view==='list'));mapButton.setAttribute('aria-pressed',String(view==='map'));panel.hidden=!hasSelectedTown()||view!=='map';list.hidden=view==='map';if(view==='list'){clearMap();summary.textContent='';return;}
summary.removeAttribute('translate');const {region,town,places}=current;panel.setAttribute('aria-label',town.name+' attraction map');const mapped=places.map(place=>({place,point:verifiedLocation(place)})).filter(p=>p.point);clearMap();summary.textContent='';
if(!mapped.length){const hasTownLocations=(current.allPlaces||places).some(place=>verifiedLocation(place));empty.querySelector('p').textContent=hasTownLocations?'No verified map locations match your current filters.':'Map locations are not available for this town yet. You can still explore all attractions in List view.';empty.hidden=false;summary.textContent=town.name+' · 0 matching verified map locations';return}
empty.hidden=true;summary.textContent=mapped.length+' of '+places.length+' matching attractions have verified map locations. All attractions remain available in List view.';
try{const L=await leaflet();if(ticket!==version||view!=='map')return;canvas.hidden=false;canvas.setAttribute('aria-label','Map of verified attractions in '+town.name);map=L.map(canvas,{scrollWheelZoom:false});const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);let tileError=false;tiles.on('tileerror',()=>{if(ticket===version&&!tileError){tileError=true;summary.textContent=(window.CompassI18n?.t(mapped.length+' of '+places.length+' matching attractions have verified map locations. All attractions remain available in List view.')||summary.textContent)+' '+(window.CompassI18n?.t('Background tiles could not be loaded. List view remains available.')||'Background tiles could not be loaded. List view remains available.');summary.setAttribute('translate','no')}});layers=L.featureGroup().addTo(map);const icon=L.divIcon({className:'town-map-pin',html:'<span aria-hidden="true"></span>',iconSize:[28,36],iconAnchor:[14,36],popupAnchor:[0,-34]});for(const {place,point}of mapped)L.marker(point,{icon,alt:place.name,title:place.name,keyboard:true}).bindPopup(popup(place,town,region),{maxWidth:260,minWidth:180}).addTo(layers);map.fitBounds(layers.getBounds(),{padding:[28,28],maxZoom:16});canvas.dataset.markerCount=String(mapped.length);map.invalidateSize();}catch{if(ticket===version){clearMap();empty.hidden=true;summary.textContent='The map could not be loaded. Please use List view.'}}
}
function select(next){if(!hasSelectedTown())return;view=next;render()}
listButton.addEventListener('click',()=>select('list'));mapButton.addEventListener('click',()=>select('map'));byId('town-map-return').addEventListener('click',()=>{select('list');listButton.focus()});
window.CompassTownMap={loading(){version++;current=null;controls.hidden=true;panel.hidden=true;empty.hidden=true;mount.replaceChildren();clearMap()},update(results){const nextKey=results?results.region.id+'/'+results.town.id:'';if(nextKey!==townKey)view='list';townKey=nextKey;current=results;render()}};
})();
