(()=>{'use strict';const places=window.COMPASS_PLACES||[],city=places.filter(p=>!p.nearby),key='cape-compass-trip-v1';let trip={stops:[],date:'',visitors:'1',pickup:''},storageAvailable=true;
try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved&&typeof saved==='object')trip={stops:Array.isArray(saved.stops)?saved.stops.filter(id=>city.some(p=>p.id===id)):[],date:typeof saved.date==='string'?saved.date:'',visitors:String(saved.visitors||'1'),pickup:typeof saved.pickup==='string'?saved.pickup:''}}catch{storageAvailable=false}
function save(){try{sessionStorage.setItem(key,JSON.stringify(trip))}catch{storageAvailable=false}if(!storageAvailable){const error=document.getElementById('form-error');if(error)error.textContent='Browser session storage is unavailable. Enable storage to retain your trip across pages.'}}
const current=city.find(p=>p.id===document.body.dataset.place);if(current&&!trip.stops.includes(current.id)){trip.stops.push(current.id);save()}
const form=document.getElementById('trip-form');if(form){const options=document.getElementById('stop-options');for(const p of city){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name='stops';input.value=p.id;input.checked=trip.stops.includes(p.id);label.append(input,document.createTextNode(p.name));options.append(label)}
const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;form.elements.date.min=today;for(const field of ['date','visitors','pickup'])form.elements[field].value=trip[field];
function read(){trip.stops=[...form.querySelectorAll('[name=stops]:checked')].map(el=>el.value);for(const field of ['date','visitors','pickup'])trip[field]=form.elements[field].value;save()}
form.addEventListener('input',read);form.addEventListener('change',read);form.addEventListener('submit',event=>{event.preventDefault();read();const error=document.getElementById('form-error');error.textContent='';if(!trip.stops.length){error.textContent='Choose at least one Cape Coast attraction.';options.querySelector('input').focus();return}if(!trip.pickup.trim()){error.textContent='Enter a pickup point within Cape Coast.';form.elements.pickup.focus();return}if(trip.date<today||!Number.isInteger(Number(trip.visitors))||+trip.visitors<1||+trip.visitors>100){error.textContent='Choose today or a future date and a whole group size from 1 to 100.';return}if(!storageAvailable)return;location.href=(document.body.dataset.place?'../':'')+'payment.html'});save()}
const search=document.getElementById('search'),category=document.getElementById('category');if(search){const cards=[...document.querySelectorAll('#city-grid .place-card')];function filter(){let count=0;for(const card of cards){const show=(card.dataset.search+" "+card.textContent.toLowerCase()).normalize("NFD").replace(/[\u0300-\u036f]/g,"").includes(search.value.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,""))&&(!category.value||card.dataset.category===category.value);card.hidden=!show;if(show)count++}document.getElementById('result-count').textContent=`${count} city ${count===1?'place':'places'}`;document.getElementById('no-results').hidden=count>0}search.addEventListener('input',filter);category.addEventListener('change',filter);document.getElementById('reset-filters').addEventListener('click',()=>{search.value='';category.value='';filter();search.focus()})}
const review=document.getElementById('trip-review');if(review){if(!trip.stops.length){review.innerHTML='<h2>Your visit starts here.</h2><p class="section-lead">Choose a Cape Coast place and add your visit details.</p><a class="button" href="index.html#planner">Plan my visit →</a>'}else{const heading=document.createElement('h2');heading.textContent='Your chosen stops';review.append(heading);for(const id of trip.stops){const p=city.find(p=>p.id===id),row=document.createElement('div'),link=document.createElement('a'),note=document.createElement('p');row.className='review-stop';link.href=`places/${p.slug}.html`;link.textContent=p.name;note.className='helper';note.textContent=p.access;row.append(link,note);review.append(row)}const dl=document.createElement('dl');dl.className='review-meta';for(const [label,value]of [['Preferred date',trip.date||'Not set'],['Visitors',trip.visitors],['Pickup point',trip.pickup||'Not set'],['Return', 'Original pickup point; time to confirm']]){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;if(label==="Pickup point")dd.setAttribute("translate","no");div.append(dt,dd);dl.append(div)}review.append(dl);const edit=document.createElement('a');edit.className='button';edit.href='index.html#planner';edit.textContent='Edit my visit';review.append(edit);const clear=document.createElement('button');clear.className='location-button';clear.textContent='Clear my trip';clear.style.display='block';clear.addEventListener('click',()=>{trip={stops:[],date:'',visitors:'1',pickup:''};save();location.reload()});review.append(clear);const note=document.createElement('p');note.className='helper';note.textContent='Stop order is not an optimised route or confirmed schedule. This plan stays in your browser session.';review.append(note)}}
})();
