(()=>{'use strict';const places=window.COMPASS_PLACES||[],tripPlaces=window.COMPASS_TRIP_PLACES||places,key='cape-compass-trip-v1';let trip={stops:[],date:'',visitors:'1',pickup:''},storageAvailable=true;
function load(){try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');trip={stops:[],date:'',visitors:'1',pickup:''};if(saved&&typeof saved==='object')trip={stops:Array.isArray(saved.stops)?saved.stops.filter(id=>tripPlaces.some(p=>p.id===id)):[],date:typeof saved.date==='string'?saved.date:'',visitors:String(saved.visitors||'1'),pickup:typeof saved.pickup==='string'?saved.pickup:''}}catch{storageAvailable=false}}
load();
const catalogueLink=document.querySelector('.all-places');if(catalogueLink){const total=new Set(tripPlaces.map(p=>p.id)).size;catalogueLink.replaceChildren(document.createTextNode(`Explore all ${total} places across Ghana `));const arrow=document.createElement('span');arrow.setAttribute('aria-hidden','true');arrow.textContent='→';catalogueLink.append(arrow)}
function save(){try{sessionStorage.setItem(key,JSON.stringify(trip));syncCardButtons();return true}catch{storageAvailable=false}const error=document.getElementById('form-error');if(error)error.textContent='Browser session storage is unavailable. Enable storage to retain your trip across pages.';return false}
const directory=document.querySelector('.regional-directory')||document.querySelector('[data-trip-actions]'),tripStatus=document.getElementById('card-trip-status');
function syncCardButtons(){if(!directory)return;for(const button of directory.querySelectorAll('[data-add-to-trip]')){const place=tripPlaces.find(p=>p.id===button.dataset.addToTrip);button.hidden=!place;if(!place)continue;const added=trip.stops.includes(place.id);const label=window.CompassI18n?.t(added?'Added ✓':'Add to trip')||(added?'Added ✓':'Add to trip');if(button.textContent!==label)button.textContent=label;button.disabled=added;button.setAttribute('aria-label',added?`${place.name} is added to your proposed trip`:`Add ${place.name} to your proposed trip`);button.classList.toggle('is-added',added)}}
function refresh(){load();syncCardButtons();const options=document.getElementById('stop-options');if(options)for(const input of options.querySelectorAll('[name=stops]')){input.checked=trip.stops.includes(input.value);if(input.checked&&input.closest('details'))input.closest('details').open=true}}
if(directory){directory.addEventListener('click',event=>{const button=event.target.closest('[data-add-to-trip]');if(!button||!directory.contains(button))return;const place=tripPlaces.find(p=>p.id===button.dataset.addToTrip);if(!place)return;load();if(trip.stops.includes(place.id)){syncCardButtons();return}const previous=trip.stops;trip.stops=[...previous,place.id];if(save()){if(tripStatus)tripStatus.textContent=`${place.name} added to your proposed trip. This is not a booking.`}else{trip.stops=previous;syncCardButtons();if(tripStatus)tripStatus.textContent='Your trip could not be saved. Enable browser session storage and try again.'}});const cardList=directory.querySelector('.region-groups');if(cardList)new MutationObserver(syncCardButtons).observe(cardList,{childList:true,subtree:true});syncCardButtons()}
document.addEventListener('compasscardsrendered',syncCardButtons);document.addEventListener('compasslanguagechange',syncCardButtons);
window.addEventListener('pageshow',refresh);window.addEventListener('storage',event=>{if(event.key===key||event.key===null)refresh()});
const form=document.getElementById('trip-form');if(form){const options=document.getElementById('stop-options'),groups=new Map();for(const p of tripPlaces){let group=groups.get(p.region);if(!group){group=document.createElement('details');group.className='trip-region';const summary=document.createElement('summary');summary.textContent=p.region;group.append(summary);options.append(group);groups.set(p.region,group)}const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name='stops';input.value=p.id;input.checked=trip.stops.includes(p.id);if(input.checked)group.open=true;label.append(input,document.createTextNode(p.name+' · '+p.town));group.append(label)}
const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;form.elements.date.min=today;for(const field of ['date','visitors','pickup'])form.elements[field].value=trip[field];
function read(){trip.stops=[...form.querySelectorAll('[name=stops]:checked')].map(el=>el.value);for(const field of ['date','visitors','pickup'])trip[field]=form.elements[field].value;save()}
form.addEventListener('input',read);form.addEventListener('change',read);form.addEventListener('submit',event=>{event.preventDefault();read();const error=document.getElementById('form-error');error.textContent='';if(!trip.stops.length){error.textContent='Choose at least one attraction.';options.querySelector('input').focus();return}if(trip.date<today||!Number.isInteger(Number(trip.visitors))||+trip.visitors<1||+trip.visitors>100){error.textContent='Choose today or a future date and a whole group size from 1 to 100.';return}if(!storageAvailable)return;location.href=(document.body.dataset.place?'../':'')+'payment.html'});save()}
const search=document.getElementById('search'),category=document.getElementById('category');if(search){const cards=[...document.querySelectorAll('#city-grid .place-card')];function filter(){let count=0;for(const card of cards){const show=(card.dataset.search+" "+card.textContent.toLowerCase()).normalize("NFD").replace(/[\u0300-\u036f]/g,"").includes(search.value.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,""))&&(!category.value||card.dataset.category===category.value);card.hidden=!show;if(show)count++}document.getElementById('result-count').textContent=`${count} city ${count===1?'place':'places'}`;document.getElementById('no-results').hidden=count>0}document.addEventListener('compasslanguagechange',filter);search.addEventListener('input',filter);category.addEventListener('change',filter);document.getElementById('reset-filters').addEventListener('click',()=>{search.value='';category.value='';filter();search.focus()})}
const review=document.getElementById('trip-review');if(review){if(!trip.stops.length){review.innerHTML='<h2>Your visit starts here.</h2><p class="section-lead">Choose places and add your visit details.</p><a class="button" href="index.html#planner">Plan my trip →</a>'}else{const heading=document.createElement('h2');heading.textContent='Your chosen stops';review.append(heading);for(const id of trip.stops){const p=tripPlaces.find(p=>p.id===id),row=document.createElement('div'),link=document.createElement('a'),note=document.createElement('p');row.className='review-stop';link.href=`places/${p.slug}.html`;link.textContent=p.name;note.className='helper';note.textContent=p.access;row.append(link,note);review.append(row)}const dl=document.createElement('dl');dl.className='review-meta';for(const [label,value]of [['Preferred date',trip.date||'Not set'],['Visitors',trip.visitors],['Pickup point',trip.pickup||'Not set'],['Transport', 'Not arranged']]){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;if(label==="Pickup point")dd.setAttribute("translate","no");div.append(dt,dd);dl.append(div)}review.append(dl);const edit=document.createElement('a');edit.className='button';edit.href='index.html#planner';edit.textContent='Edit my trip';review.append(edit);const clear=document.createElement('button');clear.className='location-button';clear.textContent='Clear my trip';clear.style.display='block';clear.addEventListener('click',()=>{trip={stops:[],date:'',visitors:'1',pickup:''};save();location.reload()});review.append(clear);const note=document.createElement('p');note.className='helper';note.textContent='Stop order is not an optimised route or confirmed schedule. This plan stays in your browser session.';review.append(note)}}
})();
