import puppeteer from '/private/tmp/two-brothers-release-tools/node_modules/puppeteer-core/lib/puppeteer/puppeteer-core.js';
const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-first-run']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});const base='http://127.0.0.1:4173';function assert(v,m){if(!v)throw Error(m)}
async function choose(code){await page.click('.language-toggle');await page.click(`[data-language="${code}"]`);await page.waitForFunction(code=>document.documentElement.lang===code,{},code)}
try{for(const width of [320,390,768,1024,1280]){await page.setViewport({width,height:900});for(const code of ['en','fr','es','de']){await page.goto(base+'/index.html');await choose(code);assert(await page.$eval('[data-language-code]',e=>e.textContent)===code.toUpperCase(),'Language code');assert(await page.$eval('.language-toggle img',img=>img.complete&&img.naturalWidth>0),'Flag loaded');for(const route of ['/index.html','/attractions.html','/places/cape-coast-castle-museum.html','/privacy.html','/payment.html']){await page.goto(base+route);await page.waitForFunction(code=>document.documentElement.lang===code,{},code);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${width} ${code} ${route}`);await page.click('.language-toggle');const box=await page.$eval('.language-menu',e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right}});assert(box.left>=0&&box.right<=width,`Menu bounds ${width} ${code}`);await page.keyboard.press('Escape');assert(await page.$eval('.language-toggle',e=>e===document.activeElement&&e.getAttribute('aria-expanded')==='false'),'Escape returns focus')}}}
await page.goto(base+'/index.html');await page.evaluate(()=>sessionStorage.clear());await page.reload();await choose('fr');assert(await page.$eval('h1',e=>e.textContent)==='Bienvenue à Cape Coast','French heading');await page.evaluate(()=>{const form=document.getElementById('trip-form');form.elements.date.value='2026-12-15';form.elements.pickup.value='My private pickup';form.requestSubmit()});await page.waitForFunction(()=>document.querySelector('#form-error').textContent==='Choisissez au moins un lieu à Cape Coast.');await page.evaluate(()=>{const form=document.getElementById('trip-form');form.querySelector('[name=stops]').checked=true;form.elements.pickup.value='My private pickup';form.dispatchEvent(new Event('input',{bubbles:true}))});const trip=await page.evaluate(()=>sessionStorage.getItem('cape-compass-trip-v1'));await choose('de');assert(await page.evaluate(()=>sessionStorage.getItem('cape-compass-trip-v1'))===trip,'Trip unchanged by language');await page.evaluate(()=>document.getElementById('trip-form').requestSubmit());await page.waitForFunction(()=>location.pathname.endsWith('/payment.html'));await page.waitForFunction(()=>document.documentElement.lang==='de');assert(await page.$eval('#trip-review',e=>e.textContent.includes('My private pickup')),'Pickup preserved');assert(await page.$eval('#trip-review h2',e=>e.textContent)==='Ihre gewählten Stopps','Translated dynamic review');
await page.goto(base+'/attractions.html');await choose('fr');await page.type('#search','patrimoine');assert(await page.$$eval('#city-grid .place-card',cards=>cards.some(c=>!c.hidden)),'French search');await page.waitForFunction(()=>/lieux? en ville/.test(document.querySelector('#result-count').textContent));
await page.goto(base+'/places/cape-coast-castle-museum.html');await page.click('[data-next]');await page.waitForFunction(()=>document.querySelector('.gallery-caption').textContent.startsWith('Canons du château'));assert(await page.$eval('.gallery-credit',e=>e.textContent.startsWith('Photo 2 sur 4.')),'Dynamic gallery credit');await choose('en');assert(await page.$eval('.gallery-caption',e=>e.textContent)==='Cape Coast Castle cannons beside the Atlantic Ocean.','English restoration');
await page.goto(base+'/index.html');await page.click('.language-toggle');await page.keyboard.press('Escape');await page.focus('.language-toggle');await page.keyboard.press('ArrowDown');assert(await page.$eval('[data-language=en]',e=>e===document.activeElement),'Keyboard opens menu');await page.keyboard.press('End');assert(await page.$eval('[data-language=de]',e=>e===document.activeElement),'Keyboard End');await page.keyboard.press('Enter');await page.waitForFunction(()=>document.documentElement.lang==='de');
await page.goto(base+'/index.html');await choose('fr');await page.setViewport({width:1280,height:900});await page.click('.language-toggle');await page.screenshot({path:'/private/tmp/cape-language-desktop.png'});await page.keyboard.press('Escape');await page.setViewport({width:390,height:844});await page.click('.language-toggle');await page.screenshot({path:'/private/tmp/cape-language-mobile.png'});
assert(!errors.length,errors.join('\n'));console.log('PASS: 100 responsive language/route views; flags, persistence, keyboard menu, French search, validation, review, gallery and trip preservation');}finally{await browser.close()}
