const fs = require('fs'), path = require('path');
const root = path.resolve(__dirname, '..');
const template = fs.readFileSync(path.join(root, 'partners.html'), 'utf8');
const policies = [
 ['terms.html', 'Terms of Service', 'Clear expectations for your visit.', [
  ['About Cape Coast Compass', 'Cape Coast Compass is a tourism information website and trip-planning preview for Cape Coast, Ghana. These terms describe use of this website. The operator is presented under the Cape Coast Compass name; no affiliation with an attraction, transport provider or public authority is implied.'],
  ['Planning is not a booking', 'Your selected stops, date, visitor count and pickup point form a proposed itinerary. The website does not send booking requests, reserve transport or admission, confirm availability, or take payments. No service contract or reservation is created by using the planner. Do not treat a saved plan as a confirmation.'],
  ['Attraction information and access', 'Descriptions and photographs are provided to help you explore possible visits. Opening times, entry charges, permissions, accessibility, capacity and conditions may change. Confirm arrangements with the relevant venue before travelling. Nearby destinations require separate arrangements and are not included in the city planner.'],
  ['Future service arrangements', 'Before a paid visit can be offered, the operator and visitor must agree in writing on availability, itinerary, pickup and return arrangements, inclusions, the total price and cancellation terms. Meals, guiding and optional activities are not included unless expressly agreed.'],
  ['Respectful and responsible use', 'Use the site lawfully. Do not interfere with its operation, submit harmful content, or misrepresent another person. At heritage sites, places of worship, markets and coastal communities, follow venue rules, respect residents, and obtain permission before photographing people.'],
  ['Photographs and website content', 'Photographs have different sources and reuse conditions. A download link does not grant a commercial licence or override a photographer’s rights. Some supplied images have been refined for colour and brightness; 8K downloads are upscaled and do not represent recovered native 8K detail. Image credits and editing notes are retained where available.'],
  ['Privacy and third-party websites', 'Read our <a href="privacy.html">Privacy Policy</a> for local trip storage and optional location access. Third-party websites and venues operate under their own policies. Cape Coast Compass does not control their services.'],
  ['Changes and questions', 'These terms may be updated as the service develops. The date below identifies this version. For questions, use the contact channel through which Cape Coast Compass shared this website with you. Please do not publish private trip details in a public message. Nothing in these terms is intended to exclude rights that applicable law does not allow to be excluded.']
 ]],
 ['privacy.html', 'Privacy Policy', 'Your trip details, explained.', [
  ['The current website', 'Cape Coast Compass currently provides information and a browser-based trip-planning preview. It has no customer accounts, booking database, advertising trackers or payment processing. This policy describes the current implementation, rather than a future booking service.'],
  ['Trip details stay in your browser', 'The planner stores chosen attraction identifiers, preferred date, number of visitors and pickup text in browser session storage under cape-compass-trip-v1. This allows your plan to continue across pages in the same browser session. These fields are not submitted to Cape Coast Compass by the current website. They are not a confirmed booking. Browser session restoration may preserve a session after a restart.'],
  ['Optional location access', 'The site requests your location only when you press “Use my current location” and your browser grants permission. It fills the pickup field with latitude and longitude and shows estimated accuracy. Coordinates can be retained with your plan in session storage. The site does not continuously track you or turn coordinates into a street address. You may enter a pickup point manually instead.'],
  ['Hosting and technical information', 'Cloudflare Pages hosts this website. When you visit, the hosting infrastructure processes technical request data such as IP address, requested URL, browser information and security-related logs to deliver and protect the site. This processing is separate from the local trip planner. See <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare’s Privacy Policy</a> for its practices. Requests may be processed through Cloudflare’s global infrastructure.'],
  ['Cookies, analytics and payments', 'The site does not set advertising or analytics cookies and does not install an analytics service. Session storage is used for the planner and is separate from cookies. Hosting or browser security features may have their own behaviour. No card numbers, payment credentials or card payments are collected here.'],
  ['Your choices and retention', 'To remove the locally saved itinerary, open <a href="payment.html">My trip</a> and select “Clear my trip”, or clear this site’s storage in your browser. Revoke location permission in browser settings at any time. Clearing the plan does not remove hosting-provider logs. We do not set or claim a retention period for Cloudflare’s infrastructure logs. Avoid entering sensitive information in the pickup field.'],
  ['Contact and privacy questions', 'For privacy questions or concerns, contact Cape Coast Compass through the channel used to share this site with you. If a request concerns local trip information, clearing browser storage is the immediate way to remove it; the current planner does not send a copy to the operator. You may also contact Ghana’s <a href="https://dataprotection.org.gh/">Data Protection Commission</a> about data protection concerns. Do not post personal information publicly.'],
  ['Future changes', 'A booking, payment, contact form or analytics integration would change how data is processed. This policy will need to be updated before those features collect information, including the operator’s contact details, purposes, recipients and retention arrangements. The date below identifies the current version.']
 ]],
 ['refund-policy.html', 'Refund Policy', 'Know the terms before you pay.', [
  ['No payments are accepted today', 'Cape Coast Compass currently operates as a planning preview. It does not accept payments, collect card details, sell admission or confirm bookings. Creating or clearing a plan carries no charge. Because this site currently collects no payment, there is no site payment to cancel or refund.'],
  ['Your proposed itinerary', 'You may edit or clear your proposed visit at any time in <a href="payment.html">My trip</a>. This does not cancel a reservation with a venue or another provider because the website has not made one.'],
  ['Payments to other providers', 'If you separately book or pay an attraction, hotel, guide or transport provider, its cancellation and refund terms apply to that transaction. Contact the provider that received the payment. A directory listing does not mean Cape Coast Compass sold, guaranteed or received payment for that service.'],
  ['Before paid bookings are introduced', 'The cancellation terms must be supplied and agreed before any future payment. They must specify cancellation deadlines, refund eligibility, any disclosed deductions, treatment of venue charges, changes, no-shows, operator cancellations and the refund method and expected processing time. No cancellation fee, refund percentage or processing deadline is currently established.'],
  ['Questions or an unexpected charge', 'Do not submit card details through this website. If you believe a payment has been associated with Cape Coast Compass, check the payment receipt and contact the named recipient through a verified channel. You may contact Cape Coast Compass through the channel used to share the site, without posting card or account information publicly.'],
  ['Policy updates', 'This policy describes the current preview. It must be replaced or expanded when a payment and booking process is introduced. Any future terms must be disclosed before payment, and nothing here is intended to remove rights that cannot be excluded under applicable law.']
 ]]
];
for (const [file, title, subtitle, sections] of policies) {
 let html = template.replace(/<title>.*?<\/title>/, `<title>${title} | Cape Coast Compass</title>`).replace(/aria-current="page"/g, '');
 const content = `<main id="main"><section class="page-heading legal-heading"><p class="eyebrow">Cape Coast Compass</p><h1>${title}</h1><p>${subtitle}</p><p class="helper">Last updated: 1 October 2026</p></section><article class="legal-content"><nav class="policy-index" aria-label="On this page"><h2>On this page</h2>${sections.map(([heading], i) => `<a href="#policy-${i + 1}">${heading}</a>`).join('')}</nav>${sections.map(([heading, text], i) => `<section id="policy-${i + 1}"><h2>${heading}</h2><p>${text}</p></section>`).join('')}<p class="legal-return"><a class="text-link" href="index.html">Return to Cape Coast Compass →</a></p></article></main>`;
 html = html.replace(/<main[\s\S]*?<\/main>/, content).replace(/<script defer[^>]*><\/script>/g, '');
 fs.writeFileSync(path.join(root, file), html);
}
let missing = template.replace(/<title>.*?<\/title>/, '<title>Page not found | Cape Coast Compass</title>').replace(/aria-current="page"/g, '').replace(/<script defer[^>]*><\/script>/g, '');
missing = missing.replace(/<main[\s\S]*?<\/main>/, '<main id="main"><section class="page-heading"><p class="eyebrow">404 · Page not found</p><h1>Let’s find your next stop.</h1><p>This page is unavailable. Explore the directory or return to the homepage.</p><p class="legal-return"><a class="button" href="attractions.html">Explore attractions →</a></p></section></main>');
fs.writeFileSync(path.join(root, '404.html'), missing);
console.log('Terms, privacy, refund policy and helpful 404 page created');
